include::{topic_page_meta}[tags="build-liquidoc-alternate-gem"]

There are two fairly common cases in which you might wish to run a version of LiquiDoc other than the latest officially released edition.
You may need a previously released version due to deprecated functionality or an unfixed bug in the latest release.
Or maybe there is functionality you need that only exists in unreleased version -- probably a version you've hacked yourself or one already pushed to GitHub but awaiting release.

Here we instruct all three use cases: <<old-version,previous release>>, <<local-mod,local modification>>, and <<remote-mod,remote modification>>.
Each method recommends editing the `Gemfile` in your root directory.
Open it with your favorite code/text editor, and remember to run `bundle update` after re-pointing your `liquidoc` dependency.

TIP: For advanced gem-version designation tricks, see link:http://bundler.io/v1.16/gemfile_man.html[Bundler's Gemfile documentation].

[[old-version]]
== Install an older gem version

If you need to invoke an older version of LiquiDoc, simply designate the required version and update your dependencies.

. In your `Gemfile`, edit the `liquidoc` line by setting a required version of the gem.
+
[source,yaml]
----
'liquidoc', '0.6.0'
----

include::{snippetsdir}/snippets.adoc[tags="instruct-gemfile-save-install"]

[[local-mod]]
== Install a local modified gem

If you have a modified clone of the `liquidoc-gem` repository on your local system, Bundler will build the gem at runtime as long as you have the `liquidoc` dependency properly designated.

. In your `Gemfile`, edit the `liquidoc` line by adding a path to your local `liquidoc-gem` repo.
+
[source,yaml]
----
'liquidoc', path: '../liquidoc-gem'
----
+
TIP: The pass value can be absolute or relative to the `Gemfile` itself.

include::{snippetsdir}/snippets.adoc[tags="instruct-gemfile-save-install"]

Subsequent `liquidoc` commands will use this alternate source.

[[remote-mod]]
== Install a remote modified gem

If you need to run a pre-release version of LiquiDoc that is posted in a remote repo, such as in a branch in the prime repo that has been submitted but not

. In your `Gemfile`, edit the `liquidoc` entry to designate a Git repo and a specific branch,
+
[source,yaml,subs="+attributes"]
----
'liquidoc', :git => "{github_git_uri}", :branch => "special-mode"
----
+
Where `special-mode` is the name of an unmerged branch you want your gem built from.
+
[TIP]
Instead of a branch, you can designate a specific revision hash with `:ref => "a3iq0k"`, where `a3iq0k` is an example partial hash, enabling you to build a gem from any past commit.
As another option, specific Git tags can be designated with a notation such as `:tag => "v1.0.0-rc"`.

include::{snippetsdir}/snippets.adoc[tags="instruct-gemfile-save-install"]
