include::{page_meta}[tags="overview-liquidoc-cmf"]

LiquiDoc CMF (LDCMF) is a “content management _framework_” -- a set of tools, conventions, and standards for sensibly organizing and maintaining source content and data as well as producing deliverable artifacts.
The {project_name} project
Here we'll preview its main features, focusing on how they're implemented in this project ({project_name}).

== LDCMF: Not Your Daddy's Content Platform

LDCMF is likely to seem unfamiliar.
It is a publishing platform but not a content management _system_ (CMS) nor a _component_ content management system (CCMS).
It differs from these mainly in that it does not revolve around a database or a user interface designed for a specific type of content or type of publishing.

LDCMF is designed for flexibility, in order to meet the demands of complex documentation projects that cover potentially numerous _versions_ of multiple _products_ for various _audiences_ yielding two or more output _formats_, as well as other complicating factors.
The platform enables a docs-as-code approach to technical content, whereby the docs source material is tied to the product source code, as well as using tools and methods more familiar to developers than to writers.

.Pros/Cons of LiquiDoc CMF vs Proprietary CMS/CCMS Solutions
****
include::{includes_dir}/ldcmf-vs-proprietary.adoc[tags="dlist"]
****

== What Do I Need to Learn?

ifdef::show_docpro[]
In your role as a documentation contributor, or _documentarian_, you will not need to know the differences between LiquiDoc, LDCMF, and your team's implementation, so this overview should suffice.
Instead, this {portal_term} will walk you through the procedures necessary to create, edit, and manage content in this particular LDCMF environment.
endif::show_docpro[]

ifdef::show_admin[]
As a LiquiDoc instance administrator, you'll need to intimately understand the relationship between LiquiDoc and LDCMF.
endif::show_admin[]

ifdef::show_dev[]
As a developer, you have the ability to extend or modify either the LiquiDoc build utility or the LDCMF content framework.

Each has a distinct Git repository.

* link:{liquidoc-gem_git_repo_url}[LiquiDoc gem repo]
* link:{liquidoc-cmf_git_repo_url}[LiquiDoc CMF repo]

To modify the *LiquiDoc* Ruby gem, you will need some familiarity with Ruby.

The *LDCMF* repo, on the other hand, is merely a set of directories, static files, and documentation.
The most complicated languages are YAML, AsciiDoc, and Liquid.

endif::show_dev[]

== LiquiDoc and LDCMF Overview

The LiquiDoc CMF platform relies on the LiquiDoc build utility, which in turn employs other open-source applications to process and render rich-text and multimedia documentation output.

As should be clear from the comparisons key to LDCMF-based documentation projects is managing all content and data in plaintext (“flat”) files rather than a database.
The primary source formats for an LDCMF project like this one ({project_name}) are *AsciiDoc* and *YAML*.

include::{includes_dir}/_built_terms.adoc[tags="asciidoc"]

include::{includes_dir}/_built_terms.adoc[tags="yaml"]

ifdef::cheat[]
[TIP]
The above definitions are included from this repo's preprocessed terms file.
In early stages of the build process, AsciiDoc files are generated from the glossary source `data/terms.yml`.
These can be printed all at once, as with the <<jargon-guide#>>, or else selectively included, as above, using:

[source,asciidoc]
----
include::{includes_dir}/_built_terms.adoc[tags="asciidoc"]

include::{includes_dir}/_built_terms.adoc[tags="yaml"]
----
endif::[]

These formats are chosen for learnability and readability, and this guide will walk you through the steps you need to get comfortable and proficient with them, including plenty of supplemental resources.
Before diving into AsciiDoc and YAML, let's keep exploring just what LDCMF is.

LiquiDoc CMF is used to build various types of documentation, but it excels at multi-format output, such as generating a PDF edition and a website _from the same source files_.


.The Intimidation Factor
****
Instead of web forms with text fields, selectboxes, and WYSIWYG editors; LDCMF offers a bunch of text files.
The advantages may not be self-evident yet, but let's address the elephant in the room: this all seems a lot harder than it should be.
It will sometimes take more work to manage docs in plaintext files using what will at first feel like crude editing tools, not to mention that clumsy command line.

While LDCMF's usability will steadily improve, it will always require technical writers and documentation managers who have worked in other fields to reconceive how docs are created and managed.
But you _will_ be able to get comfortable with your new tooling, and you might even come to appreciate it.
Nothing we can say here will take the pain away, but rest assured this documentation is written with beginners in mind.
****

// tag::admin-edit[]
== GitHub

This project is intended to be managed using *link:https://github.com[GitHub]*, the most popular cloud service for Git repository hosting.
You will need a GitHub account to fully participate as a contributor.

Unfortunately, GitHub's friendly user interface will only handle some of the procedures you need to perform in order to commit to documentation.

which manages source-code in a distributed fashion as the codebase evolves.
Managing content directly with Git allows documentation to more accurately align with the product it covers, a key objective of LDCMF.
If you have avoided Git so far, your number may be up.
There's great news: Git is a highly marketable skill with an ever-widening range of applications in various sectors, fields, and roles.
Once you experience it's potential in the world of documentation, you will understand what everyone is so excited about.
// end::admin-edit[]

// tag::admin-edit[]
In the case of the {project_name} project itself, we're generating a PDF “manual” and an HTML “portal” for each of the following “guides”:

include::../../README.adoc[tags="artifact-links"]
// end::admin-edit[]
