include::{page_meta}[tags="overview-asciidoc-preproc"]

One of the more complicated elements of the LiquiDoc CMF build process is the notion of AsciiDoc preprocessing.
Here we will break down the reasons we typically parse at least some data into AsciiDoc source during early phases of a LDCMF config.
We will also explore some strategies for preprocessing.

== Preprocessing in LiquiDoc

Any time we take data from a small-data file (such as YAML) and press it through a templating engine (such as Liquid), to finally generate an AsciiDoc (`.adoc`) file, we are carrying out AsciiDoc preprocessing.
This provides a reliable and extremely flexible means of providing some element of dynamism into our output.

In your LiquiDoc config file, preprocessing looks something like this:

[source,yaml]
----
- source: data/mydata.yml
  builds:
    - template: _templates/liquid/mytemplate.asciidoc
      output: _build/includes/_built_my-include.adoc
----

== What Preprocessing is Good For

This strategy is usually only advantageous under two conditions:

. When maintining multiple output artifacts that vary in their content, not just their format, preprocessing allows you to establish segregated sets of variables that apply only to each given artifact.

. In order to single-source product information between docs source and product source, storing said info in semi-structured data files as the canonical source is highly advantageous.

Content variables (AsciiDoc _attributes_ you call out with `{attr_name}` inside your content) are most useful under these circumstances.

The third use-case for content variables in AsciiDoc is typically just to store repeatedly used data all in one spot.
This would be either in a small-data file as described above, or as lots of attributes set at the top of the AsciiDoc index file (*inline definition*).
These examples do _not_ constitute AsciiDoc preprocessing, as we're passing variables directly into AsciiDoc.

[NOTE.tooling]
.Tooling clarity
Of the above-described options, inline definition is supported by *Asciidoctor* and loading attributes from external small-data files is a function of *LiquiDoc*, meaning both are available when you run your `asciidoctor` commands via `liquidoc`.

== The Art of Templating

Preprocessing involves templates, used to _press_ data into another textual output format.
This output can be any “flat” format, meaning readily savable in a text file as opposed to a complicated binary format.
Everthing from Markdown to XML is a flat format, and HTML is by far the most popular target format for templating engines.

In our case, the output format is AsciiDoc, a format itself associated with *early source* (like Markdown, popularly rendered into HTML for final rendering by a browser) and not *late source* (like HTML, directly rendered by the browser with no need for intermediary proceessing).
