include::{page_meta}[tags="working-includes"]

There's no way around it: developing complex documentation with AsciiDoc means using lots and lots of `include::[]` macros.
This is a necessity of [.term.ccms]#compontent content management#, and it's the backbone of our indexing system.

One of the reasons we [.grok.preprocessing]#preprocess# source files is so we can have everything where it needs to be when we need it.
Because some of our content must be parsed before it can be included, and since we do not want to mix parsed files with source files, we build into an ephemeral build directory called `_build`.
This directory then becomes the _base directory_ (`base_dir` in AsciiDoc properties) -- the path from which we draw our source for any final render operations.

Our index file (+{index_file}+) is copied from the `content/` root path to the `_build/` root path, so all of its include directives are relative to the latter.
That means every include it contains must point to a file that has been properly placed relative to the `build/` root.

Let's take a look at part of +{index_file}+:

[source,asciidoc]
----
include::../{guides_index_file}[tags="example-include"]
----

What you see above as rendered output is sourced in the _actual_ +{guides_index_file}+ for this project.
And the path calling it is defined by reading the _actual_ configuration file for this project (+{config_file}+).
And that reference to the config file's name?
You guessed it: dynamic.

[source,asciidoc]
----
And the path calling it is defined by reading the _actual_ configuration file for this project (+{config_file}+).
----
