= LiquiDoc: A framework and build tool for badass documentation

[.panel.opening#opening]
--
The tools used to document software products are finally gaining ground on the products they document.

Now they can be fully *integrated at source*, as well.
--

[.panel.dark#single-source]
--
If you have ever wished you could truly single-source your entire product the way you build your API docs right out of the source code the reference, your solution has arrived.

LiquiDoc takes your *canonical data* and generates preconfigured documentation artifacts such as responsive *websites*, *PDF* books, and even *slide decks*.
--

[.panel.light#command]
--
And it's as easy as

[source,bash]
----
$ bundle exec liquidoc -c _configs/build-docs.yml
----
--

[.panel.dark#word-salad]
--
LiquiDoc combines semi-structured datasources such as *JSON*, *XML*, *YAML*, and *CSV*, parses them into *AsciiDoc* files and variables using *Liquid* templates, then loads these and other content files (AsciiDoc or *Markdown*) into *Asciidoctor* to build PDF output via *Prawn*, websites using *Jekyll*, and slideshows using *Deck.js*.

All of this is compatible with *source/version control* systems such as *Git* and integrating with *REST APIs* like Jira, GitHub, and many others.

We know that's a mouthful.
That's kind of our point.
LiquiDoc's goal is to take any data you can throw at it and spit it out as pretty much any kind of document artifact.
--

[.panel.light#cmf]
Documentarians designed LiquiDoc and the LiquiDoc Content Management Framework (LDCMF) to tackle the extraordinary complexity of their sourcing or output needs.

LiquiDoc CMF recommends a structure and enables a procedural build flow for bootstrapping documentation projects that are embedded in product code or simply too difficult to solve with conventional docs platforms.

[.card#dac]
.Docs as Code
--
Finally combine your code and docs repositories.
--

[.card#dry]
.DRY
--
LiquiDoc is the key to true single sourcing of *docs _and_ code*.
--

[.card#adoc]
.AsciiDoc
--
The fastest-growing lightweight markup format has never been easier to implement.
--

[.card#yaml]
.YAML
--
For easily customized data structures, LiquiDoc plays nice with YAML.
--

[.card#smalldata]
.“Small Data” FTW
--
You can't go wrong keeping docpro product info in Git-friendly flat files.
--

[.card#output]
.Output: Anything, Anywhere
--
Build documents in various formats and deploy it as your needs demand.
--

[.card#open]
.LiquiDoc == Open Standards
--
We hate lock-in, and we want your data and content to be truly portable.
--

[.card#extensibility]
.True Extensibility
--
Open system commands enable execution of any third-party command-line utility, so you'll never be stuck.
--

[.card#compatibility]
.Compatibility
--
LiquiDoc plays nice with DevOps automation platforms.
--

[.card#simplicity]
.Simplicity
--
But LiquiDoc is designed to handle 99% of documentation use cases using built-in routines.
--
